version: '3.8'

services:
  create_resume:
    container_name: create_resume
    image: postgres:latest
    env_file:
      - ./.env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /data/postgres
    volumes:
      - ${DOCKER_VALUMES}
    ports:
      - ${POSTGRES_HOST}:${POSTGRES_PORT}:5432
    networks:
      - create_resume
    restart: unless-stopped

  create_resume_pgadmin:
    container_name: create_resume_pgadmin
    image: dpage/pgadmin4
    env_file:
      - ./.env
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_CONFIG_SERVER_MODE: ${PGADMIN_CONFIG_SERVER_MODE}
    volumes:
      - ${DOCKER_VALUMES}
    ports:
      - ${PGADMIN_DEFAULT_HOST}:${PGADMIN_DEFAULT_PORT}:80
    networks:
      - create_resume
    restart: unless-stopped

networks:
  create_resume:
    driver: bridge

volumes:
  postgres:
  pgadmin:
